browser=chrome
headless=true
device=mobile  # desktop, tab, mobile
baseUrl=https://rahulshettyacademy.com/loginpagePractise/
qa.baseUrl=https://rahulshettyacademy.com/loginpagePractise/
stage.baseUrl=https://rahulshettyacademy.com/loginpagePractise/
prod.baseUrl=https://rahulshettyacademy.com/loginpagePractise/
username=rahulshettyacademy
password=Learning@830$3mK2
execution=local   # local or remote
gridUrl=http://localhost:4444/wd/hub
